name: Run PHPStan (CI)

on: [ workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          path: helga-breadcrumbs

      - name: Rename install files
        shell: bash
        run: |
          cp helga-breadcrumbs/.github/resources/.composer.json.github composer.json
          cp helga-breadcrumbs/.github/resources/.phpstan.neon.github phpstan.neon

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Run Composer Install
        shell: bash
        run: |
          composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPStan
        shell: bash
        run: |
          php vendor/bin/phpstan analyze
