name: Run PHPStan (CI)

on: [ workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          path: helga-breadcrumbs

      - name: Rename install files
        shell: bash
        run: |
          cp helga-breadcrumbs/.github/resources/.composer.json.github composer.json
          cp helga-breadcrumbs/.github/resources/.phpstan.neon.github phpstan.neon

      - name: Install Composer
        uses: helga-agentur/composer-install@v4

      - name: Run PHPStan
        shell: bash
        run: |
          php vendor/bin/phpstan analyze
